// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/danjenson/motoko/motoko/internal/pb"

// TachikomaClient is an autogenerated mock type for the TachikomaClient type
type TachikomaClient struct {
	mock.Mock
}

// Infer provides a mock function with given fields: ctx, opts
func (_m *TachikomaClient) Infer(ctx context.Context, opts ...grpc.CallOption) (pb.Tachikoma_InferClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 pb.Tachikoma_InferClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) pb.Tachikoma_InferClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pb.Tachikoma_InferClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Learn provides a mock function with given fields: ctx, opts
func (_m *TachikomaClient) Learn(ctx context.Context, opts ...grpc.CallOption) (pb.Tachikoma_LearnClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 pb.Tachikoma_LearnClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) pb.Tachikoma_LearnClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pb.Tachikoma_LearnClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Predict provides a mock function with given fields: ctx, opts
func (_m *TachikomaClient) Predict(ctx context.Context, opts ...grpc.CallOption) (pb.Tachikoma_PredictClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 pb.Tachikoma_PredictClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) pb.Tachikoma_PredictClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pb.Tachikoma_PredictClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
