version: 0.1
environment_variables:
  git-credential-helper: true
phases:
  build:
    commands:
      - echo build
  post_build:
    commands:
      - bash -c 'if [ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]; then exit 1; fi'
      - echo post build
