#!/bin/bash
set -e

pp () {
  printf "\n\n$1\n"
}

pp 'logging in to AWS ECR'
aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 902096072945.dkr.ecr.us-west-1.amazonaws.com
pp 'building docker image'
docker build -t motoko .
pp 'tagging docker image as latest'
docker tag motoko:latest 902096072945.dkr.ecr.us-west-1.amazonaws.com/motoko:latest
pp 'pushing latest docker image to AWS ECR'
docker push 902096072945.dkr.ecr.us-west-1.amazonaws.com/motoko:latest
