AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: motoko-backend

Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        RUN_MODE: prod

Resources:
  MotokoGraphQL:
    Type: AWS::Serverless::Function
    Role: arn:aws:iam::902096072945:role/motoko-lambda
    Properties:
      FunctionName: motoko-graphql
      Role: arn:aws:iam::902096072945:role/motoko-lambda
      Environment:
        Variables:
          RUST_BACKTRACE: 1
      CodeUri: rs/graphql
      Handler: bootstrap.is.real.handler
      Runtime: provided
    Metadata:
      BuildMethod: makefile
  MotokoGarbageCollect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: motoko-garbage-collect
      Role: arn:aws:iam::902096072945:role/motoko-lambda
      Environment:
        Variables:
          RUST_BACKTRACE: 1
      CodeUri: rs/graphql
      Handler: bootstrap.is.real.handler
      Runtime: provided
    Metadata:
      BuildMethod: makefile
  MotokoURIToSQLDB:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: motoko-uri-to-sql-db
      Role: arn:aws:iam::902096072945:role/motoko-lambda
      CodeUri: py/uri-to-sql-db
      Handler: app.lambda_handler
      Runtime: python3.8
  MotokoPlot:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: motoko-plot
      Role: arn:aws:iam::902096072945:role/motoko-lambda
      MemorySize: 1024
      CodeUri: py/plot
      Handler: app.lambda_handler
      Runtime: python3.8
  MotokoInvalidateCache:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: motoko-invalidate-cache
      Role: arn:aws:iam::902096072945:role/motoko-lambda
      CodeUri: py/invalidate-cache
      Handler: app.lambda_handler
      Runtime: python3.8
