#!/bin/sh

function get_commit {
    git log --oneline -- $1 | head -n 1 | cut -d " " -f1
}

ROOT_COMMIT=$(get_commit)
SUBDIR_COMMIT=$(get_commit backend/rs/graphql)

STATUS=0
if [ "$SUBDIR_COMMIT" == "$ROOT_COMMIT" ]; then
  cd backend/rs/graphql && cargo test
  STATUS=$?
fi
exit $STATUS
