[package]
name = "motoko"
version = "0.1.0"
authors = ["Daniel Jenson <daniel.a.jenson@gmail.com>"]
edition = "2018"
description = "commands for orchestrating the motoko project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.1", features = ["yaml"] }
which = "4.0.1"
reqwest = { version = "0.10.7", features = ["blocking"] }
regex = "1.3.9"
